-- drop constraints before making changes
ALTER TABLE queue DROP FOREIGN KEY fk_queue_parent_queue_id;
ALTER TABLE assignment DROP FOREIGN KEY fk_assignment_queue;

-- delete the old queues
DELETE FROM queue;

-- add the new queues
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 1,"all","All Participants",NULL,0,NULL,"All participants in the database." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 2,"finished","Finished all questionnaires",NULL,0,1,"Participants who have completed all questionnaires." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 3,"ineligible","Not eligible to answer questionnaires",NULL,0,1,"Participants who are not eligible to answer questionnaires due to a permanent condition, because they are inactive or because they do not have a phone number." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 4,"inactive","Inactive participants",NULL,0,3,"Participants who are not eligible for answering questionnaires because they have been marked as inactive." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 5,"sourcing required","Participants without a phone number",NULL,0,3,"Participants who are not eligible for answering questionnaires because they have no active phone numbers." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 6,"refused consent","Participants who refused consent",NULL,0,3,"Participants who are not eligible for answering questionnaires because they have refused consent." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 7,"deceased","Deceased participants",NULL,0,3,"Participants who are not eligible for answering questionnaires because they are deceased." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 8,"deaf","Deaf participants",NULL,0,3,"Participants who are not eligible for answering questionnaires because they are hard of hearing." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 9,"mentally unfit","Mentally unfit participants",NULL,0,3,"Participants who are not eligible for answering questionnaires because they are mentally unfit." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 10,"language barrier","Participants with a language barrier",NULL,0,3,"Participants who are not eligible for answering questionnaires because of a language barrier." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 11,"age range","Participants whose age is outside of the valid range",NULL,0,3,"Participants who are not eligible for answering questionnaires because their age is not within the valid range." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 12,"other","Participants with an undefined condition",NULL,0,3,"Participants who are not eligible for answering questionnaires because they have been identified to have an undefined condition (other)." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 13,"eligible","Eligible to answer questionnaires",NULL,0,1,"Participants who are eligible to answer questionnaires." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 14,"qnaire","Questionnaire",NULL,1,13,"Eligible participants who are currently assigned to the questionnaire." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 15,"restricted","Restricted from calling",NULL,1,14,"Eligible participants whose city, province or postcode have been restricted." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 16,"qnaire waiting","Waiting to begin",NULL,1,14,"Eligible participants who are waiting the scheduled cool-down period before beginning the questionnaire." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 17,"assigned","Currently assigned",NULL,1,14,"Eligible participants who are currently assigned to an operator." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 18,"not assigned","Not assigned",NULL,1,14,"Eligible participants who are not assigned to an operator." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 19,"appointment","Participants with appointments",NULL,1,18,"Participants who have an (unassigned) appointment." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 20,"upcoming appointment","Appointment upcoming",NULL,1,19,"Participants who have an appointment in the future." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 21,"assignable appointment","Appointment assignnable",1,1,19,"Participants who have an immediate appointment which is ready to be assigned." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 22,"missed appointment","Appointment missed",2,1,19,"Participants who have an appointment which was missed." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 23,"no appointment","Participants without appointments",NULL,1,18,"Participants who do not have an appointment." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 24,"new participant","Never assigned participants",NULL,1,23,"Participants who have never been assigned to an operator." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 25,"new participant outside calling time","New participants, outside calling time",NULL,1,24,"New participants whose local time is outside of the valid calling hours." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 26,"new participant within calling time","New participants, within calling time",NULL,1,24,"New participants whose local time is within the valid calling hours." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 27,"new participant not available","New participants, not available",NULL,1,26,"New participants who are not available." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 28,"new participant available","New participants, available",21,1,26,"New participants who are available." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 29,"new participant always available","New participants always available",22,1,26,"New participants who are always available." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 30,"old participant","Previously assigned participants",NULL,1,23,"Participants who have been previously assigned." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 31,"contacted","Last call: contacted",NULL,1,30,"Participants who's last call result was 'contacted'." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 32,"contacted waiting","Last call: contacted (waiting)",NULL,1,31,"Participants who's last call result was 'contacted' and the scheduled call back time has not yet been reached." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 33,"contacted ready","Last call: contacted (ready)",NULL,1,31,"Participants who's last call result was 'contacted' and the scheduled call back time has been reached." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 34,"contacted outside calling time","Last call: contacted (outside calling time)",NULL,1,33,"Participants who's last call result was 'contacted', the scheduled call back time has been reached and the participant's local time is outside of valid calling times." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 35,"contacted within calling time","Last call: contacted (within calling time)",NULL,1,33,"Participants who's last call result was 'contacted', the scheduled call back time has been reached and the participant is within valid calling times." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 36,"contacted not available","Last call: contacted (not available)",NULL,1,35,"Participants who's last call result was 'contacted', the scheduled call back time has been reached and the participant is within valid calling times." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 37,"contacted available","Last call: contacted (available)",3,1,35,"Available participants who's last call result was 'contacted', the scheduled call back time has been reached and the participant is within valid calling times." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 38,"contacted always available","Last call: contacted (always available)",4,1,35,"Always available participants who's last call result was 'contacted', the scheduled call back time has been reached and the participant is within valid calling times." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 39,"busy","Last call: busy line",NULL,1,30,"Participants who's last call result was 'busy'." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 40,"busy waiting","Last call: busy line (waiting)",NULL,1,39,"Participants who's last call result was 'busy' and the scheduled call back time has not yet been reached." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 41,"busy ready","Last call: busy line (ready)",NULL,1,39,"Participants who's last call result was 'busy' and the scheduled call back time has been reached." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 42,"busy outside calling time","Last call: busy (outside calling time)",NULL,1,41,"Participants who's last call result was 'busy', the scheduled call back time has been reached and the participant's local time is outside of valid calling times." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 43,"busy within calling time","Last call: busy (within calling time)",NULL,1,41,"Participants who's last call result was 'busy', the scheduled call back time has been reached and the participant is within valid calling times." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 44,"busy not available","Last call: busy (not available)",NULL,1,43,"Unavailable participants who's last call result was 'busy', the scheduled call back time has been reached and the participant is within valid calling times." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 45,"busy available","Last call: busy (available)",5,1,43,"Available participants who's last call result was 'busy', the scheduled call back time has been reached and the participant is within valid calling times." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 46,"busy always available","Last call: busy (always available)",6,1,43,"Always available participants who's last call result was 'busy', the scheduled call back time has been reached and the participant is within valid calling times." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 47,"fax","Last call: fax line",NULL,1,30,"Participants who's last call result was 'fax'." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 48,"fax waiting","Last call: fax line (waiting)",NULL,1,47,"Participants who's last call result was 'fax' and the scheduled call back time has not yet been reached." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 49,"fax ready","Last call: fax line (ready)",NULL,1,47,"Participants who's last call result was 'fax' and the scheduled call back time has been reached." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 50,"fax outside calling time","Last call: contacted (outside calling time)",NULL,1,49,"Participants who's last call result was 'fax', the scheduled call back time has been reached and the participant's local time is outside of valid calling times." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 51,"fax within calling time","Last call: fax (within calling time)",NULL,1,49,"Participants who's last call result was 'fax', the scheduled call back time has been reached and the participant is within valid calling times." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 52,"fax not available","Last call: fax (not available)",NULL,1,51,"Unavailable participants who's last call result was 'fax', the scheduled call  back time has been reached and the participant is within valid calling times." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 53,"fax available","Last call: fax (available)",7,1,51,"Available participants who's last call result was 'fax', the scheduled call  back time has been reached and the participant is within valid calling times." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 54,"fax always available","Last call: fax (always available)",8,1,51,"Always available participants who's last call result was 'fax', the scheduled call back time has been reached and the participant is within valid calling times." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 55,"not reached","Last call: not reached",NULL,1,30,"Participants who's last call result was 'not reached'." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 56,"not reached waiting","Last call: not reached (waiting)",NULL,1,55,"Participants who's last call result was 'not reached' and the scheduled call back time has not yet been reached." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 57,"not reached ready","Last call: not reached (ready)",NULL,1,55,"Participants who's last call result was 'not reached' and the scheduled call back time has been reached." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 58,"not reached outside calling time","Last call: not reached (outside calling time)",NULL,1,57,"Participants who's last call result was 'not reached', the scheduled call back time has been reached and the participant's local time is outside of valid calling times." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 59,"not reached within calling time","Last call: not reached (within calling time)",NULL,1,57,"Participants who's last call result was 'not reached', the scheduled call back time has been reached and the participant is within valid calling times." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 60,"not reached not available","Last call: not reached (not available)",NULL,1,59,"Unavailable participants who's last call result was 'not reached', the scheduled call back time has been reached and the participant is within valid calling times." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 61,"not reached available","Last call: not reached (available)",9,1,59,"Available participants who's last call result was 'not reached', the scheduled call back time has been reached and the participant is within valid calling times." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 62,"not reached always available","Last call: not reached (always available)",10,1,59,"Always available participants who's last call result was 'not reached', the scheduled call back time has been reached and the participant is within valid calling times." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 63,"no answer","Last call: no answer",NULL,1,30,"Participants who's last call result was 'no answer'." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 64,"no answer waiting","Last call: no answer (waiting)",NULL,1,63,"Participants who's last call result was 'no answer' and the scheduled call back time has not yet been reached." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 65,"no answer ready","Last call: no answer (ready)",NULL,1,63,"Participants who's last call result was 'no answer' and the scheduled call back time has been reached." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 66,"no answer outside calling time","Last call: no answer (outside calling time)",NULL,1,65,"Participants who's last call result was 'no answer', the scheduled call time has been reached and the participant's local time is outside of valid calling times." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 67,"no answer within calling time","Last call: no answer (within calling time)",NULL,1,65,"Participants who's last call result was 'no answer', the scheduled call back time has been reached and the participant's local time is within valid calling times." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 68,"no answer not available","Last call: no answer (not available)",NULL,1,67,"Unavailable participants who's last call result was 'no answer', the scheduled call back time has been reached and the participant's local time is within valid calling times." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 69,"no answer available","Last call: no answer (available)",11,1,67,"Available participants who's last call result was 'no answer', the scheduled call back time has been reached and the participant's local time is within valid calling times." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 70,"no answer always available","Last call: no answer (always available)",12,1,67,"Always available participants who's last call result was 'no answer', the scheduled call back time has been reached and the participant's local time is within valid calling times." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 71,"machine message","Last call: answering machine, message left",NULL,1,30,"Participants who's last call result was 'machine message'." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 72,"machine message waiting","Last call: answering machine, message left (waiting)",NULL,1,71,"Participants who's last call result was 'machine message' and the scheduled call back time has not yet been reached." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 73,"machine message ready","Last call: answering machine, message left (ready)",NULL,1,71,"Participants who's last call result was 'machine message' and the scheduled call back time has been reached." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 74,"machine message outside calling time","Last call: machine message (outside calling time)",NULL,1,73,"Participants who's last call result was 'machine message', the scheduled call back time has been reached and the participant's local time is outside of valid calling times." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 75,"machine message within calling time","Last call: machine message (within calling time)",NULL,1,73,"Participants who's last call result was 'machine message', the scheduled call back time has been reached and the participant's local time is within valid calling times." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 76,"machine message not available","Last call: answering machine, message left (not available)",NULL,1,75,"Unavailable participants who's last call result was 'machine message', the scheduled call back time has been reached and the participant's local time is within valid calling times." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 77,"machine message available","Last call: answering machine, message left (available)",13,1,75,"Available participants who's last call result was 'machine message', the scheduled call back time has been reached and the participant's local time is within valid calling times." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 78,"machine message always available","Last call: answering machine, message left (always available)",14,1,75,"Always available participants who's last call result was 'machine message', the scheduled call back time has been reached and the participant's local time is within valid calling times." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 79,"machine no message","Last call: answering machine, message not left",NULL,1,30,"Participants who's last call result was 'machine no message'." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 80,"machine no message waiting","Last call: answering machine, message not left (waiting)",NULL,1,79,"Participants who's last call result was 'machine no message' and the scheduled call back time has not yet been reached." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 81,"machine no message ready","Last call: answering machine, message not left (ready)",NULL,1,79,"Participants who's last call result was 'machine no message' and the scheduled call back time has been reached." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 82,"machine no message outside calling time","Last call: machine no message (outside calling time)",NULL,1,81,"Participants who's last call result was 'machine no message', the scheduled call back time has been reached and the participant's local time is outside of valid calling times." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 83,"machine no message within calling time","Last call: machine no message (within calling time)",NULL,1,81,"Participants who's last call result was 'machine no message', the scheduled call back time has been reached and the participant's local time is within valid calling times." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 84,"machine no message not available","Last call: answering machine, message not left (not available)",NULL,1,83,"Unavailable participants who's last call result was 'machine no message', the scheduled call back time has been reached and the participant's local time is within valid calling times." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 85,"machine no message available","Last call: answering machine, message not left (available)",15,1,83,"Available participants who's last call result was 'machine no message', the scheduled call back time has been reached and the participant's local time is within valid calling times." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 86,"machine no message always available","Last call: answering machine, message not left (always available)",16,1,83,"Always available participants who's last call result was 'machine no message', the scheduled call back time has been reached and the participant's local time is within valid calling times." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 87,"hang up","Last call: hang up",NULL,1,30,"Participants who's last call result was 'hang up'." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 88,"hang up waiting","Last call: hang up (waiting)",NULL,1,87,"Participants who's last call result was 'hang up' and the scheduled call back time has not yet been reached." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 89,"hang up ready","Last call: hang up (ready)",NULL,1,87,"Participants who's last call result was 'hang up' and the scheduled call back time has been reached." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 90,"hang up outside calling time","Last call: hang up (outside calling time)",NULL,1,89,"Participants who's last call result was 'hang up', the scheduled call back time has been reached and the participant's local time is outside of valid calling times." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 91,"hang up within calling time","Last call: hang up (within calling time)",NULL,1,89,"Participants who's last call result was 'hang up', the scheduled call back time has been reached and the participant's local time is within valid calling times." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 92,"hang up not available","Last call: hang up (not available)",NULL,1,91,"Unavailable participants who's last call result was 'hang up', the scheduled call back time has been reached and the participant's local time is within valid calling times." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 93,"hang up available","Last call: hang up (available)",17,1,91,"Available participants who's last call result was 'hang up', the scheduled call back time has been reached and the participant's local time is within valid calling times." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 94,"hang up always available","Last call: hang up (always available)",18,1,91,"Always available participants who's last call result was 'hang up', the scheduled call back time has been reached and the participant's local time is within valid calling times." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 95,"soft refusal","Last call: soft refusal",NULL,1,30,"Participants who's last call result was 'soft refusal'." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 96,"soft refusal waiting","Last call: soft refusal (waiting)",NULL,1,95,"Participants who's last call result was 'soft refusal' and the scheduled call back time has not yet been reached." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 97,"soft refusal ready","Last call: soft refusal (ready)",NULL,1,95,"Participants who's last call result was 'soft refusal' and the scheduled call back time has been reached." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 98,"soft refusal outside calling time","Last call: soft refusal (outside calling time)",NULL,1,97,"Participants who's last call result was 'soft refusal', the scheduled call back time has been reached and the participant's local time is outside of valid calling times." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 99,"soft refusal within calling time","Last call: soft refusal (within calling time)",NULL,1,97,"Participants who's last call result was 'soft refusal', the scheduled call back time has been reached and the participant's local time within of valid calling times." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 100,"soft refusal not available","Last call: soft refusal (not available)",NULL,1,99,"Unavailable participants who's last call result was 'soft refusal', the scheduled call back time has been reached and the participant's local time within of valid calling times." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 101,"soft refusal available","Last call: soft refusal (available)",19,1,99,"Available participants who's last call result was 'soft refusal', the scheduled call back time has been reached and the participant's local time within of valid calling times." );
INSERT INTO queue ( id, name, title, rank, qnaire_specific, parent_queue_id, description ) VALUES ( 102,"soft refusal always available","Last call: soft refusal (always available)",20,1,99,"Always available participants who's last call result was 'soft refusal', the scheduled call back time has been reached and the participant's local time within of valid calling times." );

-- update the new queue IDs
UPDATE queue SET id = 1 WHERE name = "all";
UPDATE queue SET id = 2 WHERE name = "finished";
UPDATE queue SET id = 3 WHERE name = "ineligible";
UPDATE queue SET id = 4 WHERE name = "inactive";
UPDATE queue SET id = 5 WHERE name = "sourcing required";
UPDATE queue SET id = 6 WHERE name = "refused consent";
UPDATE queue SET id = 7 WHERE name = "deceased";
UPDATE queue SET id = 8 WHERE name = "deaf";
UPDATE queue SET id = 9 WHERE name = "mentally unfit";
UPDATE queue SET id = 10 WHERE name = "language barrier";
UPDATE queue SET id = 11 WHERE name = "age range";
UPDATE queue SET id = 12 WHERE name = "other";
UPDATE queue SET id = 13 WHERE name = "eligible";
UPDATE queue SET id = 14 WHERE name = "qnaire";
UPDATE queue SET id = 15 WHERE name = "restricted";
UPDATE queue SET id = 16 WHERE name = "qnaire waiting";
UPDATE queue SET id = 17 WHERE name = "assigned";
UPDATE queue SET id = 18 WHERE name = "not assigned";
UPDATE queue SET id = 19 WHERE name = "appointment";
UPDATE queue SET id = 20 WHERE name = "upcoming appointment";
UPDATE queue SET id = 21 WHERE name = "assignable appointment";
UPDATE queue SET id = 22 WHERE name = "missed appointment";
UPDATE queue SET id = 23 WHERE name = "no appointment";
UPDATE queue SET id = 24 WHERE name = "new participant";
UPDATE queue SET id = 25 WHERE name = "new participant outside calling time";
UPDATE queue SET id = 26 WHERE name = "new participant within calling time";
UPDATE queue SET id = 27 WHERE name = "new participant not available";
UPDATE queue SET id = 28 WHERE name = "new participant available";
UPDATE queue SET id = 29 WHERE name = "new participant always available";
UPDATE queue SET id = 30 WHERE name = "old participant";
UPDATE queue SET id = 31 WHERE name = "contacted";
UPDATE queue SET id = 32 WHERE name = "contacted waiting";
UPDATE queue SET id = 33 WHERE name = "contacted ready";
UPDATE queue SET id = 34 WHERE name = "contacted outside calling time";
UPDATE queue SET id = 35 WHERE name = "contacted within calling time";
UPDATE queue SET id = 36 WHERE name = "contacted not available";
UPDATE queue SET id = 37 WHERE name = "contacted available";
UPDATE queue SET id = 38 WHERE name = "contacted always available";
UPDATE queue SET id = 39 WHERE name = "busy";
UPDATE queue SET id = 40 WHERE name = "busy waiting";
UPDATE queue SET id = 41 WHERE name = "busy ready";
UPDATE queue SET id = 42 WHERE name = "busy outside calling time";
UPDATE queue SET id = 43 WHERE name = "busy within calling time";
UPDATE queue SET id = 44 WHERE name = "busy not available";
UPDATE queue SET id = 45 WHERE name = "busy available";
UPDATE queue SET id = 46 WHERE name = "busy always available";
UPDATE queue SET id = 47 WHERE name = "fax";
UPDATE queue SET id = 48 WHERE name = "fax waiting";
UPDATE queue SET id = 49 WHERE name = "fax ready";
UPDATE queue SET id = 50 WHERE name = "fax outside calling time";
UPDATE queue SET id = 51 WHERE name = "fax within calling time";
UPDATE queue SET id = 52 WHERE name = "fax not available";
UPDATE queue SET id = 53 WHERE name = "fax available";
UPDATE queue SET id = 54 WHERE name = "fax always available";
UPDATE queue SET id = 55 WHERE name = "not reached";
UPDATE queue SET id = 56 WHERE name = "not reached waiting";
UPDATE queue SET id = 57 WHERE name = "not reached ready";
UPDATE queue SET id = 58 WHERE name = "not reached outside calling time";
UPDATE queue SET id = 59 WHERE name = "not reached within calling time";
UPDATE queue SET id = 60 WHERE name = "not reached not available";
UPDATE queue SET id = 61 WHERE name = "not reached available";
UPDATE queue SET id = 62 WHERE name = "not reached always available";
UPDATE queue SET id = 63 WHERE name = "no answer";
UPDATE queue SET id = 64 WHERE name = "no answer waiting";
UPDATE queue SET id = 65 WHERE name = "no answer ready";
UPDATE queue SET id = 66 WHERE name = "no answer outside calling time";
UPDATE queue SET id = 67 WHERE name = "no answer within calling time";
UPDATE queue SET id = 68 WHERE name = "no answer not available";
UPDATE queue SET id = 69 WHERE name = "no answer available";
UPDATE queue SET id = 70 WHERE name = "no answer always available";
UPDATE queue SET id = 71 WHERE name = "machine message";
UPDATE queue SET id = 72 WHERE name = "machine message waiting";
UPDATE queue SET id = 73 WHERE name = "machine message ready";
UPDATE queue SET id = 74 WHERE name = "machine message outside calling time";
UPDATE queue SET id = 75 WHERE name = "machine message within calling time";
UPDATE queue SET id = 76 WHERE name = "machine message not available";
UPDATE queue SET id = 77 WHERE name = "machine message available";
UPDATE queue SET id = 78 WHERE name = "machine message always available";
UPDATE queue SET id = 79 WHERE name = "machine no message";
UPDATE queue SET id = 80 WHERE name = "machine no message waiting";
UPDATE queue SET id = 81 WHERE name = "machine no message ready";
UPDATE queue SET id = 82 WHERE name = "machine no message outside calling time";
UPDATE queue SET id = 83 WHERE name = "machine no message within calling time";
UPDATE queue SET id = 84 WHERE name = "machine no message not available";
UPDATE queue SET id = 85 WHERE name = "machine no message available";
UPDATE queue SET id = 86 WHERE name = "machine no message always available";
UPDATE queue SET id = 87 WHERE name = "hang up";
UPDATE queue SET id = 88 WHERE name = "hang up waiting";
UPDATE queue SET id = 89 WHERE name = "hang up ready";
UPDATE queue SET id = 90 WHERE name = "hang up outside calling time";
UPDATE queue SET id = 91 WHERE name = "hang up within calling time";
UPDATE queue SET id = 92 WHERE name = "hang up not available";
UPDATE queue SET id = 93 WHERE name = "hang up available";
UPDATE queue SET id = 94 WHERE name = "hang up always available";
UPDATE queue SET id = 95 WHERE name = "soft refusal";
UPDATE queue SET id = 96 WHERE name = "soft refusal waiting";
UPDATE queue SET id = 97 WHERE name = "soft refusal ready";
UPDATE queue SET id = 98 WHERE name = "soft refusal outside calling time";
UPDATE queue SET id = 99 WHERE name = "soft refusal within calling time";
UPDATE queue SET id = 100 WHERE name = "soft refusal not available";
UPDATE queue SET id = 101 WHERE name = "soft refusal available";
UPDATE queue SET id = 102 WHERE name = "soft refusal always available";

-- update the assignments with the new queue IDs
UPDATE assignment SET queue_id = 102 where queue_id = 82;
UPDATE assignment SET queue_id = 101 where queue_id = 81;
UPDATE assignment SET queue_id = 94 where queue_id = 76;
UPDATE assignment SET queue_id = 93 where queue_id = 75;
UPDATE assignment SET queue_id = 86 where queue_id = 70;
UPDATE assignment SET queue_id = 85 where queue_id = 69;
UPDATE assignment SET queue_id = 78 where queue_id = 64;
UPDATE assignment SET queue_id = 77 where queue_id = 63;
UPDATE assignment SET queue_id = 70 where queue_id = 58;
UPDATE assignment SET queue_id = 69 where queue_id = 57;
UPDATE assignment SET queue_id = 62 where queue_id = 52;
UPDATE assignment SET queue_id = 61 where queue_id = 51;
UPDATE assignment SET queue_id = 54 where queue_id = 46;
UPDATE assignment SET queue_id = 53 where queue_id = 45;
UPDATE assignment SET queue_id = 46 where queue_id = 40;
UPDATE assignment SET queue_id = 45 where queue_id = 39;
UPDATE assignment SET queue_id = 38 where queue_id = 34;
UPDATE assignment SET queue_id = 37 where queue_id = 33;
UPDATE assignment SET queue_id = 29 where queue_id = 27;
UPDATE assignment SET queue_id = 28 where queue_id = 26;

-- add back in the constraints
ALTER TABLE queue ADD CONSTRAINT fk_queue_parent_queue_id FOREIGN KEY(parent_queue_id) REFERENCES queue (id) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE assignment ADD CONSTRAINT fk_assignment_queue FOREIGN KEY (queue_id) REFERENCES queue (id) ON DELETE NO ACTION ON UPDATE NO ACTION;
