#!/usr/bin/php
<?php
/** 
 * Utility which changes the version tag value
 * @author Patrick Emond <emondpd@mcmaster.ca>
 * @param string version
 */

$filename = 'settings.ini.php';

// validate arguments
if( 2 < $argc )
{
  print "Script expects one optional argument: the new version.\n";
  exit( 1 );
}

// validate new version number
$new_version = array_key_exists( 1, $argv ) ? $argv[1] : NULL;
if( !is_null( $new_version ) && preg_match( '/[^0-9a-z.]/', $new_version ) )
{
  print "Version numbers must only contain numbers, lowercase letters and periods.\n";
  exit( 2 );
}

// get the build number
$new_build = exec( 'git rev-parse --short HEAD' );

// make sure ini file exists (checking ./ and ../)
if( !file_exists( $filename ) ) $filename = '../'.$filename;

if( !file_exists( $filename ) )
{
  print "Cannot find ini file.\n";
  exit( 3 );
}

// replace the general-version settings in the main ini file
$contents = file_get_contents( $filename );

$new_contents = preg_replace( "/(SETTINGS\['general'\]\['build'\]) = '[^']*'/",
                              "\\1 = '$new_build'",
                              $contents,
                              1 );

if( !is_null( $new_version ) )
{
  $new_contents = preg_replace( "/(SETTINGS\['general'\]\['version'\]) = '[^']*'/",
                                "\\1 = '$new_version'",
                                $contents,
                                1 );
}

// result will be NULL if an error occurred
if( is_null( $new_contents ) )
{
  print "The script failed to change the version.\n";
  exit( 4 );
}

// open the ini file for writing
$handler = fopen( $filename, 'w' );
if( !$handler )
{
  print "Unable to open ini file for writing.\n";
  exit( 5 );
}

// write the new version to the ini file
$result = fwrite( $handler, $new_contents );
if( !$result )
{
  print "Unable to write new version to ini file.\n";
  exit( 6 );
}

if( !fclose( $handler ) )
{
  print "Unable to close file after writing new version.\n";
  exit( 7 );
}

if( !is_null( $new_version ) ) print "Successfully bumped version to $new_version\n";
print "Build changed to $new_build\n";
