#!/usr/bin/php
<?php
/** 
 * Utility which rewrites all minified versions of javascript files which are out of date
 * @author Patrick Emond <emondpd@mcmaster.ca>
 * @param string version
 */

// make sure to be in the web directory
if( 'aux' == basename( getcwd() ) ) chdir( '..' );
if( !file_exists( 'web' ) )
{
  print "Cannot find web directory\n";
  exit( 1 );
}
chdir( 'web' );

$file_list = array();
exec( implode( ' | ', array(
  'find -type f',
  'grep "\.js\|\.css$"',
  'grep -v "^\.\/lib"',
  'grep -v "\.\/app\/require.js$"',
  'grep -v "theme.css"',
  'grep -v "\.min\."',
  'grep -v "\.swp"'
) ), $file_list );

foreach( $file_list as $file )
{
  $file_type = false === strpos( $file, '.js' ) ? 'css' : 'js';
  if( 'js' == $file_type ) $min_file = str_replace( '.js', '.min.js', $file );
  if( 'css' == $file_type ) $min_file = str_replace( '.css', '.min.css', $file );

  // if the minified file doesn't exist or is older than the file, re-create it
  if( !file_exists( $min_file ) || filemtime( $file ) > filemtime( $min_file ) )
  {
    printf( "Creating %s\n", preg_replace( '/^\./', 'web', $min_file ) );
    exec( sprintf( 'uglify%s %s > %s', $file_type, $file, $min_file ) );
  }
}

print "Done, all files minified\n";
