#!/usr/bin/php
<?php
/** 
 * Utility which changes the bootstrap (UI) theme by number
 * @author Patrick Emond <emondpd@mcmaster.ca>
 * @param string version
 */

// validate arguments
if( 2 != $argc )
{
  print "Script expects exactly one argument: the name of the theme.\n";
  exit( 1 );
}

if( 'aux' == end( explode( '/', getcwd() ) ) ) chdir( '..' );
$theme = $argv[1];

// get cenozo aux directory (where the themes are)
include( 'settings.local.ini.php' );
$from_dir = $SETTINGS['path']['CENOZO'].'/aux';
$to_dir = 'web/css';

// see if the theme exists
$filename = sprintf( '%s/theme/theme%s.css', $from_dir, $theme );
if( !file_exists( $filename ) )
{
  print "Theme \"$theme\" doesn't exist.\n";
  exit( 2 );
}

// copy the theme
if( !copy( $filename, sprintf( '%s/theme.css', $to_dir ) ) )
{
  print "Unable to overwrite base theme file.\n";
  exit( 3 );
}

print "Successfully changed to theme \"$theme\".\n";
