#!/bin/sh
# 
# build_dox
# 
# Builds API documentation for Sabretooth using Doxygen.
# @author Patrick Emond <emondpd@mcmaster.ca>

if [ ! -d "doxygen" ]; then
  # create doxygen/ if id doesn't already exist
  mkdir doxygen
else
  # clean out doxygen/ of old files
  rm -rf doxygen/*
fi

# generate the documentation
doxygen config.dox
