#!/bin/sh
# 
# build_dox
# 
# Builds API documentation for Sabretooth using PHPUML.
# @author Patrick Emond <emondpd@mcmaster.ca>

if [ ! -d "phpuml" ]; then
  # create phpuml/ if id doesn't already exist
  mkdir phpuml
else
  # clean out phpuml/ of old files
  rm -rf phpuml/*
fi

# generate the documentation
phpuml ../api/ -f htmlnew -o phpuml --no-deployment-view
