CREATE TABLE recording (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  update_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  create_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  rank INT(11) NOT NULL,
  name VARCHAR(45) NOT NULL,
  record TINYINT(1) NOT NULL,
  timer INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX uq_rank (rank ASC),
  UNIQUE INDEX uq_name (name ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;
