CREATE TABLE setting (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  update_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  create_timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  site_id INT(10) UNSIGNED NOT NULL,
  mail_name VARCHAR(255) NULL DEFAULT NULL,
  mail_address VARCHAR(127) NULL DEFAULT NULL,
  call_without_webphone TINYINT(1) NOT NULL DEFAULT 0,
  calling_start_time TIME NOT NULL DEFAULT '09:00:00',
  calling_end_time TIME NOT NULL DEFAULT '21:00:00',
  appointment_duration INT(10) UNSIGNED NOT NULL DEFAULT 60,
  pre_call_window INT(10) UNSIGNED NOT NULL DEFAULT 5,
  post_call_window INT(10) UNSIGNED NOT NULL DEFAULT 15,
  contacted_wait INT(10) UNSIGNED NOT NULL DEFAULT 10080,
  busy_wait INT(10) UNSIGNED NOT NULL DEFAULT 15,
  fax_wait INT(10) UNSIGNED NOT NULL DEFAULT 15,
  no_answer_wait INT(10) UNSIGNED NOT NULL DEFAULT 1440,
  not_reached_wait INT(10) UNSIGNED NOT NULL DEFAULT 4320,
  hang_up_wait INT(10) UNSIGNED NOT NULL DEFAULT 2880,
  soft_refusal_wait INT(10) UNSIGNED NOT NULL DEFAULT 525600,
  PRIMARY KEY (id),
  UNIQUE INDEX uq_site_id (site_id ASC),
  INDEX fk_site_id (site_id ASC),
  CONSTRAINT fk_setting_site_id
    FOREIGN KEY (site_id)
    REFERENCES cenozo.site (id)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;
