DROP PROCEDURE IF EXISTS patch_language;
DELIMITER //
CREATE PROCEDURE patch_language()
  BEGIN

    -- determine the @cenozo database name
    SET @cenozo = (
      SELECT unique_constraint_schema
      FROM information_schema.referential_constraints
      WHERE constraint_schema = DATABASE()
      AND constraint_name = "fk_role_has_operation_role_id" );

    SELECT "Creating new language table" AS "";

    SET @test = (
      SELECT COUNT(*)
      FROM information_schema.TABLES
      WHERE TABLE_SCHEMA = @cenozo
      AND TABLE_NAME = "language" );
    IF @test = 0 THEN
      SET @sql = CONCAT(
        "CREATE TABLE IF NOT EXISTS ", @cenozo, ".language ( ",
          "id INT UNSIGNED NOT NULL AUTO_INCREMENT, ",
          "update_timestamp TIMESTAMP NOT NULL, ",
          "create_timestamp TIMESTAMP NOT NULL, ",
          "name VARCHAR(45) NOT NULL, ",
          "active TINYINT(1) NOT NULL DEFAULT 0, ",
          "code CHAR(2) NOT NULL, ",
          "PRIMARY KEY (id), ",
          "UNIQUE INDEX uq_name (name ASC), ",
          "UNIQUE INDEX uq_code (code ASC)) ",
        "ENGINE = InnoDB" );
      PREPARE statement FROM @sql;
      EXECUTE statement;
      DEALLOCATE PREPARE statement;

      SET @sql = CONCAT(
        "INSERT IGNORE INTO ", @cenozo, ".language( name, active, code ) VALUES ",
        "( 'Afar', 0, 'aa' ), ",
        "( 'Abkhazian', 0, 'ab' ), ",
        "( 'Afrikaans', 0, 'af' ), ",
        "( 'Akan', 0, 'ak' ), ",
        "( 'Albanian', 0, 'sq' ), ",
        "( 'Amharic', 0, 'am' ), ",
        "( 'Arabic', 0, 'ar' ), ",
        "( 'Aragonese', 0, 'an' ), ",
        "( 'Armenian', 0, 'hy' ), ",
        "( 'Assamese', 0, 'as' ), ",
        "( 'Avaric', 0, 'av' ), ",
        "( 'Avestan', 0, 'ae' ), ",
        "( 'Aymara', 0, 'ay' ), ",
        "( 'Azerbaijani', 0, 'az' ), ",
        "( 'Bashkir', 0, 'ba' ), ",
        "( 'Bambara', 0, 'bm' ), ",
        "( 'Basque', 0, 'eu' ), ",
        "( 'Belarusian', 0, 'be' ), ",
        "( 'Bengali', 0, 'bn' ), ",
        "( 'Bihari languages', 0, 'bh' ), ",
        "( 'Bislama', 0, 'bi' ), ",
        "( 'Tibetan', 0, 'bo' ), ",
        "( 'Bosnian', 0, 'bs' ), ",
        "( 'Breton', 0, 'br' ), ",
        "( 'Bulgarian', 0, 'bg' ), ",
        "( 'Burmese', 0, 'my' ), ",
        "( 'Catalan; Valencian', 0, 'ca' ), ",
        "( 'Czech', 0, 'cs' ), ",
        "( 'Chamorro', 0, 'ch' ), ",
        "( 'Chechen', 0, 'ce' ), ",
        "( 'Chinese', 0, 'zh' ), ",
        "( 'Church Slavic; Old Slavonic', 0, 'cu' ), ",
        "( 'Chuvash', 0, 'cv' ), ",
        "( 'Cornish', 0, 'kw' ), ",
        "( 'Corsican', 0, 'co' ), ",
        "( 'Cree', 0, 'cr' ), ",
        "( 'Welsh', 0, 'cy' ), ",
        "( 'Czech', 0, 'cs' ), ",
        "( 'Danish', 0, 'da' ), ",
        "( 'German', 0, 'de' ), ",
        "( 'Divehi; Dhivehi; Maldivian', 0, 'dv' ), ",
        "( 'Dutch; Flemish', 0, 'nl' ), ",
        "( 'Dzongkha', 0, 'dz' ), ",
        "( 'Greek, Modern (1453-)', 0, 'el' ), ",
        "( 'English', 1, 'en' ), ",
        "( 'Esperanto', 0, 'eo' ), ",
        "( 'Estonian', 0, 'et' ), ",
        "( 'Basque', 0, 'eu' ), ",
        "( 'Ewe', 0, 'ee' ), ",
        "( 'Faroese', 0, 'fo' ), ",
        "( 'Persian', 0, 'fa' ), ",
        "( 'Fijian', 0, 'fj' ), ",
        "( 'Finnish', 0, 'fi' ), ",
        "( 'French', 1, 'fr' ), ",
        "( 'Western Frisian', 0, 'fy' ), ",
        "( 'Fulah', 0, 'ff' ), ",
        "( 'Georgian', 0, 'ka' ), ",
        "( 'German', 0, 'de' ), ",
        "( 'Gaelic; Scottish Gaelic', 0, 'gd' ), ",
        "( 'Irish', 0, 'ga' ), ",
        "( 'Galician', 0, 'gl' ), ",
        "( 'Manx', 0, 'gv' ), ",
        "( 'Greek, Modern (1453-)', 0, 'el' ), ",
        "( 'Guarani', 0, 'gn' ), ",
        "( 'Gujarati', 0, 'gu' ), ",
        "( 'Haitian; Haitian Creole', 0, 'ht' ), ",
        "( 'Hausa', 0, 'ha' ), ",
        "( 'Hebrew', 0, 'he' ), ",
        "( 'Herero', 0, 'hz' ), ",
        "( 'Hindi', 0, 'hi' ), ",
        "( 'Hiri Motu', 0, 'ho' ), ",
        "( 'Croatian', 0, 'hr' ), ",
        "( 'Hungarian', 0, 'hu' ), ",
        "( 'Armenian', 0, 'hy' ), ",
        "( 'Igbo', 0, 'ig' ), ",
        "( 'Icelandic', 0, 'is' ), ",
        "( 'Ido', 0, 'io' ), ",
        "( 'Sichuan Yi; Nuosu', 0, 'ii' ), ",
        "( 'Inuktitut', 0, 'iu' ), ",
        "( 'Interlingue; Occidental', 0, 'ie' ), ",
        "( 'Interlingua', 0, 'ia' ), ",
        "( 'Indonesian', 0, 'id' ), ",
        "( 'Inupiaq', 0, 'ik' ), ",
        "( 'Icelandic', 0, 'is' ), ",
        "( 'Italian', 0, 'it' ), ",
        "( 'Javanese', 0, 'jv' ), ",
        "( 'Japanese', 0, 'ja' ), ",
        "( 'Kalaallisut; Greenlandic', 0, 'kl' ), ",
        "( 'Kannada', 0, 'kn' ), ",
        "( 'Kashmiri', 0, 'ks' ), ",
        "( 'Georgian', 0, 'ka' ), ",
        "( 'Kanuri', 0, 'kr' ), ",
        "( 'Kazakh', 0, 'kk' ), ",
        "( 'Central Khmer', 0, 'km' ), ",
        "( 'Kikuyu; Gikuyu', 0, 'ki' ), ",
        "( 'Kinyarwanda', 0, 'rw' ), ",
        "( 'Kirghiz; Kyrgyz', 0, 'ky' ), ",
        "( 'Komi', 0, 'kv' ), ",
        "( 'Kongo', 0, 'kg' ), ",
        "( 'Korean', 0, 'ko' ), ",
        "( 'Kuanyama; Kwanyama', 0, 'kj' ), ",
        "( 'Kurdish', 0, 'ku' ), ",
        "( 'Lao', 0, 'lo' ), ",
        "( 'Latin', 0, 'la' ), ",
        "( 'Latvian', 0, 'lv' ), ",
        "( 'Limburgan; Limburger; Limburgish', 0, 'li' ), ",
        "( 'Lingala', 0, 'ln' ), ",
        "( 'Lithuanian', 0, 'lt' ), ",
        "( 'Luxembourgish; Letzeburgesch', 0, 'lb' ), ",
        "( 'Luba-Katanga', 0, 'lu' ), ",
        "( 'Ganda', 0, 'lg' ), ",
        "( 'Macedonian', 0, 'mk' ), ",
        "( 'Marshallese', 0, 'mh' ), ",
        "( 'Malayalam', 0, 'ml' ), ",
        "( 'Maori', 0, 'mi' ), ",
        "( 'Marathi', 0, 'mr' ), ",
        "( 'Malay', 0, 'ms' ), ",
        "( 'Macedonian', 0, 'mk' ), ",
        "( 'Malagasy', 0, 'mg' ), ",
        "( 'Maltese', 0, 'mt' ), ",
        "( 'Mongolian', 0, 'mn' ), ",
        "( 'Maori', 0, 'mi' ), ",
        "( 'Malay', 0, 'ms' ), ",
        "( 'Burmese', 0, 'my' ), ",
        "( 'Nauru', 0, 'na' ), ",
        "( 'Navajo; Navaho', 0, 'nv' ), ",
        "( 'Ndebele, South; South Ndebele', 0, 'nr' ), ",
        "( 'Ndebele, North; North Ndebele', 0, 'nd' ), ",
        "( 'Ndonga', 0, 'ng' ), ",
        "( 'Nepali', 0, 'ne' ), ",
        "( 'Dutch; Flemish', 0, 'nl' ), ",
        "( 'Norwegian Nynorsk; Nynorsk, Norwegian', 0, 'nn' ), ",
        "( 'Bokmål, Norwegian; Norwegian Bokmål', 0, 'nb' ), ",
        "( 'Norwegian', 0, 'no' ), ",
        "( 'Chichewa; Chewa; Nyanja', 0, 'ny' ), ",
        "( 'Occitan (post 1500)', 0, 'oc' ), ",
        "( 'Ojibwa', 0, 'oj' ), ",
        "( 'Oriya', 0, 'or' ), ",
        "( 'Oromo', 0, 'om' ), ",
        "( 'Ossetian; Ossetic', 0, 'os' ), ",
        "( 'Panjabi; Punjabi', 0, 'pa' ), ",
        "( 'Persian', 0, 'fa' ), ",
        "( 'Pali', 0, 'pi' ), ",
        "( 'Polish', 0, 'pl' ), ",
        "( 'Portuguese', 0, 'pt' ), ",
        "( 'Pushto; Pashto', 0, 'ps' ), ",
        "( 'Quechua', 0, 'qu' ), ",
        "( 'Romansh', 0, 'rm' ), ",
        "( 'Romanian; Moldavian; Moldovan', 0, 'ro' ), ",
        "( 'Romanian; Moldavian; Moldovan', 0, 'ro' ), ",
        "( 'Rundi', 0, 'rn' ), ",
        "( 'Russian', 0, 'ru' ), ",
        "( 'Sango', 0, 'sg' ), ",
        "( 'Sanskrit', 0, 'sa' ), ",
        "( 'Sinhala; Sinhalese', 0, 'si' ), ",
        "( 'Slovak', 0, 'sk' ), ",
        "( 'Slovak', 0, 'sk' ), ",
        "( 'Slovenian', 0, 'sl' ), ",
        "( 'Northern Sami', 0, 'se' ), ",
        "( 'Samoan', 0, 'sm' ), ",
        "( 'Shona', 0, 'sn' ), ",
        "( 'Sindhi', 0, 'sd' ), ",
        "( 'Somali', 0, 'so' ), ",
        "( 'Sotho, Southern', 0, 'st' ), ",
        "( 'Spanish; Castilian', 0, 'es' ), ",
        "( 'Albanian', 0, 'sq' ), ",
        "( 'Sardinian', 0, 'sc' ), ",
        "( 'Serbian', 0, 'sr' ), ",
        "( 'Swati', 0, 'ss' ), ",
        "( 'Sundanese', 0, 'su' ), ",
        "( 'Swahili', 0, 'sw' ), ",
        "( 'Swedish', 0, 'sv' ), ",
        "( 'Tahitian', 0, 'ty' ), ",
        "( 'Tamil', 0, 'ta' ), ",
        "( 'Tatar', 0, 'tt' ), ",
        "( 'Telugu', 0, 'te' ), ",
        "( 'Tajik', 0, 'tg' ), ",
        "( 'Tagalog', 0, 'tl' ), ",
        "( 'Thai', 0, 'th' ), ",
        "( 'Tibetan', 0, 'bo' ), ",
        "( 'Tigrinya', 0, 'ti' ), ",
        "( 'Tonga (Tonga Islands)', 0, 'to' ), ",
        "( 'Tswana', 0, 'tn' ), ",
        "( 'Tsonga', 0, 'ts' ), ",
        "( 'Turkmen', 0, 'tk' ), ",
        "( 'Turkish', 0, 'tr' ), ",
        "( 'Twi', 0, 'tw' ), ",
        "( 'Uighur; Uyghur', 0, 'ug' ), ",
        "( 'Ukrainian', 0, 'uk' ), ",
        "( 'Urdu', 0, 'ur' ), ",
        "( 'Uzbek', 0, 'uz' ), ",
        "( 'Venda', 0, 've' ), ",
        "( 'Vietnamese', 0, 'vi' ), ",
        "( 'Volapük', 0, 'vo' ), ",
        "( 'Welsh', 0, 'cy' ), ",
        "( 'Walloon', 0, 'wa' ), ",
        "( 'Wolof', 0, 'wo' ), ",
        "( 'Xhosa', 0, 'xh' ), ",
        "( 'Yiddish', 0, 'yi' ), ",
        "( 'Yoruba', 0, 'yo' ), ",
        "( 'Zhuang; Chuang', 0, 'za' ), ",
        "( 'Chinese', 0, 'zh' ), ",
        "( 'Zulu', 0, 'zu' )" );
      PREPARE statement FROM @sql;
      EXECUTE statement;
      DEALLOCATE PREPARE statement;

    END IF;

  END //
DELIMITER ;

CALL patch_language();
DROP PROCEDURE IF EXISTS patch_language;
