-- -----------------------------------------------------
-- Queues
-- -----------------------------------------------------
SET AUTOCOMMIT=0;

-- define the interview queues

INSERT INTO queue( name, view, description )
VALUES( "Missed", "queue_missed",
"Participants with missed appointments.  This list is generated by searching for all
participants who have appointments in the past but were never reached by an operator." );

INSERT INTO queue( name, view, description )
VALUES( "Appointment", "queue_appointment",
"Participants with an upcomming appointment.  This list is generated by searching for all
participants which have appointments in the future (whether they have been assigned to an
operator in the past or not)." );

INSERT INTO queue( name, view, description )
VALUES( "Available", "queue_available",
"Participants with specific availability. This list is generated by searching for all
participants who have been assigned in the past and which have one or more specific
availability times." );

INSERT INTO queue( name, view, description )
VALUES( "Busy", "queue_busy",
"Participants who when previously contacted were not reached the operator got a busy signal.
This status is associated with a callback delay time.  Once the delay time has been reached
the participant will be included in this queue.  Furthermore, if this call status reaches a
defined limit then the participant is removed from this queue." );

INSERT INTO queue( name, view, description )
VALUES( "Fax", "queue_fax",
"Participants who when previously contacted were not reached the operator was connected to
a fax machine.  This status is associated with a callback delay time.  Once the delay time
has been reached the participant will be included in this queue.  Furthermore, if this call
status reaches a defined limit then the participant is removed from this queue." );

INSERT INTO queue( name, view, description )
VALUES( "No Answer", "queue_no_answer",
"Participants who when previously contacted were not reached there was no answer.  This
status is associated with a callback delay time.  Once the delay time has been reached the
participant will be included in this queue.  Furthermore, if this call status reaches a
defined limit then the participant is removed from this queue." );

INSERT INTO queue( name, view, description )
VALUES( "Machine Message", "queue_machine_message",
"Participants who when previously contacted were not reached the operator was connected to
an answering machine and left a message.  This status is associated with a callback delay
time.  Once the delay time has been reached the participant will be included in this queue.
Furthermore, if this call status reaches a defined limit then the participant is removed
from this queue." );

INSERT INTO queue( name, view, description )
VALUES( "Machine No Message", "queue_machine_no_message",
"Participants who when previously contacted were not reached, the operator was connected to
an answering machine and no message was left.  This status is associated with a callback
delay time.  Once the delay time has been reached the participant will be included in this
queue.  Furthermore, if this call status reaches a defined limit then the participant is
removed from this queue." );

INSERT INTO queue( name, view, description )
VALUES( "General Available", "queue_general_available",
"Participants who have not yet been contacted and have availability times.  This list is
generated by searching for all participants who have never been assigned to an operator. And
who have at least one availability entry." );

INSERT INTO queue( name, view, description )
VALUES( "General", "queue_general",
"Participants who have not yet been contacted.  This list is generated by searching for all
participants who have never been assigned to an operator.  This list does not include
participants with availability times." );

COMMIT;
