-- -----------------------------------------------------
-- Queues
-- -----------------------------------------------------
SET AUTOCOMMIT=0;

-- define the interview queues

INSERT INTO queue( name, view, description )
VALUES( "Missed", "queue_missed",
"Participants with missed appointments.  This list is generated by searching for all
participants which have appointments in the past.  When the appointment time (on any day)
occurs the participant is contacted with the purpose of scheduling a new appointment." );

INSERT INTO queue( name, view, description )
VALUES( "Appointment", "queue_appointment",
"Participants with an upcomming appointment.  This list is generated by searching for all
participants which have appointments in the future.  When the appointment time occurs the
participant is contacted and the associated interview is continued at it's current phase.
If a connection is made then the appointment is cleared from the system." );

INSERT INTO queue( name, view, description )
VALUES( "Available", "queue_available",
"Participants with specific availability. This list is generated by searching for all
participants which have one or more specific availability times and have started an interview
associated with the current site.  When the availability time occurs the participant is
contacted and the associated interview is continued at it's current phase." );

INSERT INTO queue( name, view, description )
VALUES( "Busy", "queue_busy",
"Participants who have previously been contacted.  This list in generated by searching for
all participants which, when last called, the line was busy.  This status is associated with
a delay time.  Once the delay time has been reached they are contacted again.  Furthermore,
if the number of consecutive busy calls reaches a defined limit then the participant is
removed from this queue." );

INSERT INTO queue( name, view, description )
VALUES( "Fax", "queue_fax",
"Participants who have previously been contacted.  This list in generated by searching for
all participants which, when last called, a fax machine answered the call.  This status is
associated with a delay time.  Once the delay time has been reached they are contacted
again.  Furthermore, if the number of consecutive fax calls reaches a defined limit then
the participant is removed from this queue." );

INSERT INTO queue( name, view, description )
VALUES( "No Answer", "queue_no_answer",
"Participants who have previously been contacted.  This list in generated by searching for
all participants which, when last called, there was no answer.  This status is associated
with a delay time.  Once the delay time has been reached they are contacted again.
Furthermore, if the number of consecutive no answer calls reaches a defined limit then the
participant is removed from this queue." );

INSERT INTO queue( name, view, description )
VALUES( "Machine Message", "queue_machine_message",
"Participants who have previously been contacted.  This list in generated by searching for
all participants which, when last called, an answering machine picked up the call and an
message was left.  This status is associated with a delay time.  Once the delay time has
been reached they are contacted again.  Furthermore, if the number of consecutive answering
machine calls reaches a defined limit then the participant is removed from this queue." );

INSERT INTO queue( name, view, description )
VALUES( "Machine No Message", "queue_machine_no_message",
"Participants who have previously been contacted.  This list in generated by searching for
all participants which, when last called, an answering machine picked up the call and an
message was NOT left.  This status is associated with a delay time.  Once the delay time has
been reached they are contacted again.  Furthermore, if the number of consecutive answering
machine calls reaches a defined limit then the participant is removed from this queue." );

INSERT INTO queue( name, view, description )
VALUES( "General", "queue_general",
"Participants who have not yet been contacted.  This list is generated by searching for all
participants who have never been called.  This list does not include participants with
availability times." );

COMMIT;
