-- -----------------------------------------------------
-- Queues
-- -----------------------------------------------------
SET AUTOCOMMIT=0;

-- define the interview queues
INSERT INTO queue( name, view, description )
VALUES( "Missed", "queue_missed",
"Participants with missed appointments.  This list is generated by searching for all
participants which have appointments in the past.  When the appointment time (on any day)
occurs the participant is contacted with the purpose of scheduling a new appointment." );
INSERT INTO queue( name, view, description )
VALUES( "Appointments", "queue_appointment",
"Participants with an upcomming appointment.  This list is generated by searching for all
participants which have appointments in the future.  When the appointment time occurs the
participant is contacted and the associated interview is continued at it's current phase.
If a connection is made then the appointment is cleared from the system." );
INSERT INTO queue( name, view, description )
VALUES( "Available", "queue_available",
"Participants with specific availability. This list is generated by searching for all
participants which have one or more specific availability times and have started an interview
associated with the current site.  When the availability time occurs the participant is
contacted and the associated interview is continued at it's current phase." );
INSERT INTO queue( name, view, description )
VALUES( "Previous: Busy", "queue_previous_busy",
"Participants who have previously been contacted.  This list in generated by searching for
all participants which have been previously contacted with the outcome of the call being a
busy line.  This status is associated with a delay time.  Once the delay time has been reached
they are contacted again." );
INSERT INTO queue( name, view, description )
VALUES( "Previous: No Answer", "queue_previous_no_answer",
"Participants who have previously been contacted.  This list in generated by searching for
all participants which have been previously contacted with the outcome of the call being a
ring-out.  This status is associated with a delay time.  Once the delay time has been reached
they are contacted again." );
INSERT INTO queue( name, view, description )
VALUES( "Previous: Answering Machine", "queue_previous_answering_machine",
"Participants who have previously been contacted.  This list in generated by searching for
all participants which have been previously contacted with the outcome of the call being an
answering machine.  This status is associated with a delay time.  Once the delay time has
been reached they are contacted again." );
INSERT INTO queue( name, view, description )
VALUES( "Previous: Fax", "queue_previous_fax",
"Participants who have previously been contacted.  This list in generated by searching for
all participants which have been previously contacted with the outcome of the call being a
fax machine.  This status is associated with a delay time.  Once the delay time has been
reached they are contacted again." );
INSERT INTO queue( name, view, description )
VALUES( "General", "queue_general",
"Participants who have not yet been contacted.  This list is generated by searching for all
participants who have never been called.  This list does not include participants with
availability times." );

COMMIT;
