<?php
/**
 * sabretooth.ini.php
 * 
 * Defines initialization settings for sabretooth.
 * DO NOT edit this file, to override these settings use sabretooth.local.ini.php instead.  Any
 * changes in the local ini file will override the settings found here.
 * 
 * @author Patrick Emond <emondpd@mcmaster.ca>
 * @package sabretooth
 */
namespace sabretooth;

$SETTINGS[ 'api_path' ] = '~/files/repositories/sabretooth/initial_design/api';
$SETTINGS[ 'doc_path' ] = '~/files/repositories/sabretooth/initial_design/doc';
$SETTINGS[ 'sql_path' ] = '~/files/repositories/sabretooth/initial_design/sql';
$SETTINGS[ 'tpl_path' ] = '~/files/repositories/sabretooth/initial_design/tpl';
?>
